### ISSUE TITLE
YAML configuration file

### ISSUE THREAD

**Issue by craigmaloney** [craigmaloney/pygame_photobooth#1]
Would be nice for most of the functionality to be configured using a YAML configuration file.

**Comment by craigmaloney** [comment]
Items for configuration:

* Fullscreen / Windowed
* Location to store the photos
* Camera information (and how to determine this).

**Comment by craigmaloney** [comment]
* Whether to leave the background in or not

**Comment by waldo323** [comment]
which device the Arduino is on

**Comment by craigmaloney** [comment]
Added basic configuration support (including themes). Closing this issue.
